/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.keirobm.editorminecraft.gui;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JEditorPane;
import javax.swing.JTextPane;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import org.keirobm.editorminecraft.Main;

/**
 *
 * @author Angel
 */
public class FormManual extends javax.swing.JDialog {

    /**
     * Creates new form FormManual
     */
    public FormManual(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        cargarTexto(txtIntroduccion, Main.class.getResource("manual/introduccion.html"));
        cargarTexto(txtEditarPlano, Main.class.getResource("manual/editandoPlano.html"));
        cargarTexto(txtCapas, Main.class.getResource("manual/capas.html"));
        cargarTexto(txtEstadisticas, Main.class.getResource("manual/estadisticas.html"));
        cargarTexto(txtGuardarAbrir, Main.class.getResource("manual/archivo.html"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIntroduccion = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtEditarPlano = new javax.swing.JEditorPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCapas = new javax.swing.JEditorPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtEstadisticas = new javax.swing.JEditorPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtGuardarAbrir = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manual del Editor Minecraft");
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(380, 380));

        jPanel1.setLayout(new java.awt.BorderLayout());

        txtIntroduccion.setEditable(false);
        txtIntroduccion.setContentType("text/html"); // NOI18N
        txtIntroduccion.setText("<html>\n    <head>\n        <title></title>\n    </head>\n    <body>\n    </body>\n</html>");
        txtIntroduccion.setToolTipText("");
        jScrollPane2.setViewportView(txtIntroduccion);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Introduccion", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        txtEditarPlano.setEditable(false);
        txtEditarPlano.setContentType("text/html"); // NOI18N
        txtEditarPlano.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n      \r<h1>Titulo 1 </h1>\n       <h2> Titulo 2 </h2>\n       <b> Negrita </b>\n    </p>\r\n  </body>\r\n</html>\r\n");
        txtEditarPlano.setToolTipText("");
        jScrollPane3.setViewportView(txtEditarPlano);

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Editando el Plano", jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        txtCapas.setEditable(false);
        txtCapas.setContentType("text/html"); // NOI18N
        txtCapas.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n      \r<h1>Titulo 1 </h1>\n       <h2> Titulo 2 </h2>\n       <b> Negrita </b>\n    </p>\r\n  </body>\r\n</html>\r\n");
        txtCapas.setToolTipText("");
        jScrollPane4.setViewportView(txtCapas);

        jPanel3.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Capas", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        txtEstadisticas.setEditable(false);
        txtEstadisticas.setContentType("text/html"); // NOI18N
        txtEstadisticas.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n      \r<h1>Titulo 1 </h1>\n       <h2> Titulo 2 </h2>\n       <b> Negrita </b>\n    </p>\r\n  </body>\r\n</html>\r\n");
        txtEstadisticas.setToolTipText("");
        jScrollPane5.setViewportView(txtEstadisticas);

        jPanel4.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Estadisticas", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        txtGuardarAbrir.setEditable(false);
        txtGuardarAbrir.setContentType("text/html"); // NOI18N
        txtGuardarAbrir.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n      \r<h1>Titulo 1 </h1>\n       <h2> Titulo 2 </h2>\n       <b> Negrita </b>\n    </p>\r\n  </body>\r\n</html>\r\n");
        txtGuardarAbrir.setToolTipText("");
        jScrollPane6.setViewportView(txtGuardarAbrir);

        jPanel5.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Menu Archivo", jPanel5);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Rellena un control JTextPane con el texto del archivo dado por filename
     * @param textView Control a rellenar
     * @param filename Ruta al archivo con el texto con el cual rellenar el control
     */
    private void cargarTexto(JEditorPane textView, URL filename) {
        BufferedReader lector = null;
        try {
            lector = new BufferedReader(new InputStreamReader(filename.openStream()));
            
            String leido = "";
            String readed;
            while ((readed = lector.readLine())!=null) {
                leido+=readed + "\n";
            }
            
            textView.setText(leido);   
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormManual.class.getName()).log(Level.SEVERE, "No se encontro el archivo " + filename, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormManual.class.getName()).log(Level.SEVERE, "Error en la lectura del archivo" + filename, ex);
        } finally {
            if (lector!=null) {
                try {
                    lector.close();
                } catch (IOException ex) {
                    Logger.getLogger(FormManual.class.getName()).log(Level.SEVERE, "Error al cerrar el archivo" + filename, ex);
                }
            }
        }
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JEditorPane txtCapas;
    private javax.swing.JEditorPane txtEditarPlano;
    private javax.swing.JEditorPane txtEstadisticas;
    private javax.swing.JEditorPane txtGuardarAbrir;
    private javax.swing.JEditorPane txtIntroduccion;
    // End of variables declaration//GEN-END:variables

    
}
